# Generated by Django 3.2.6 on 2021-08-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='title2',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='title1',
        ),
        migrations.AddField(
            model_name='blog',
            name='img',
            field=models.ImageField(help_text='Blog post image ', null=True, upload_to='blog_post/', verbose_name='Post Image'),
        ),
    ]
