# Generated by Django 3.2.6 on 2021-08-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_blog_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='img',
            field=models.ImageField(help_text='Blog post image ', null=True, upload_to='blog_post/', verbose_name='Post Image'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(help_text='Blog title for this particular blog', max_length=200, null=True, unique=True, verbose_name='Blog Title'),
        ),
    ]
