# Generated by Django 3.2.6 on 2021-09-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20210827_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='My_Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(help_text='the name of the car', max_length=250, null=True, verbose_name='Car Name')),
                ('price_tag', models.PositiveIntegerField(help_text='the price tag of the current car', null=True, verbose_name='Price')),
                ('img1', models.ImageField(help_text='the first image of the car', null=True, upload_to='car_images/', verbose_name='Image 1')),
                ('img2', models.ImageField(help_text='the second image of the car', null=True, upload_to='car_images/', verbose_name='Image 2')),
                ('img3', models.ImageField(help_text='the third image of the car', null=True, upload_to='car_images/', verbose_name='Image 3')),
                ('gear', models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], help_text='the gear of the current car', max_length=250, null=True, verbose_name='Car Gear')),
                ('door', models.CharField(help_text='the door of the current car', max_length=10, null=True, verbose_name='Car Door')),
                ('color', models.CharField(help_text='the color of the car', max_length=250, null=True, verbose_name='Car Color')),
                ('spear_tyre', models.BooleanField(default=False, help_text='the current status of the car spear tyre', null=True, verbose_name='Spear Tyre')),
                ('description', models.TextField(help_text='the description of the car', null=True, verbose_name='Description of the car')),
            ],
            options={
                'verbose_name': 'My Car',
                'verbose_name_plural': 'My Car',
            },
        ),
    ]
