# Generated by Django 3.2.6 on 2021-09-13 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('balance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(help_text='the user order id', max_length=500, null=True, verbose_name='User Order ID')),
                ('billing_name', models.CharField(help_text='the billing name', max_length=500, null=True, verbose_name='Billing Name')),
                ('date', models.DateTimeField(auto_now_add=True, help_text='The transaction date time ', null=True, verbose_name='Transaction Date')),
                ('amount', models.FloatField(help_text='The total amount been paid by the user', null=True, verbose_name='Amount Been Paid')),
                ('status', models.CharField(help_text='The status of the transaction', max_length=500, null=True, verbose_name='Status')),
                ('payment_method', models.CharField(default='Online Payment', help_text='The payment method for the order', max_length=500, null=True, verbose_name='Payment Method')),
                ('user_id', models.ForeignKey(help_text='The user', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'All Transactions',
                'verbose_name_plural': 'All Transactions',
            },
        ),
    ]
